# Use the official Windows Server Core image as the base image
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Set up environment variables
ENV VS_VERSION=17.9
ENV VS_INSTALLER_URL=https://download.visualstudio.microsoft.com/download/pr/12345678-1234-1234-1234-123456789012/1234567890abcdef1234567890abcdef/vs_Enterprise.exe

# Download and install Visual Studio 2022
RUN powershell -Command \
    Invoke-WebRequest -Uri $env:VS_INSTALLER_URL -OutFile vs_installer.exe ; \
    Start-Process -Wait -FilePath .\vs_installer.exe -ArgumentList '--quiet', '--norestart', '--wait', '--add', 'Microsoft.VisualStudio.Workload.ManagedDesktop', '--add', 'Microsoft.VisualStudio.Workload.NetWeb', '--add', 'Microsoft.VisualStudio.Workload.Universal', '--add', 'Microsoft.VisualStudio.Workload.NetCrossPlat', '--add', 'Microsoft.VisualStudio.Workload.Azure', '--add', 'Microsoft.VisualStudio.Workload.Data', '--add', 'Microsoft.VisualStudio.Workload.Node', '--add', 'Microsoft.VisualStudio.Workload.Office', '--add', 'Microsoft.VisualStudio.Workload.Python', '--add', 'Microsoft.VisualStudio.Workload.VisualStudioExtension', '--add', 'Microsoft.VisualStudio.Workload.NetCoreTools', '--add', 'Microsoft.VisualStudio.Workload.ManagedGame', '--add', 'Microsoft.VisualStudio.Workload.NativeDesktop', '--add', 'Microsoft.VisualStudio.Workload.NativeGame', '--add', 'Microsoft.VisualStudio.Workload.NativeMobile', '--add', 'Microsoft.VisualStudio.Workload.NativeCrossPlat', '--add', 'Microsoft.VisualStudio.Workload.UniversalBuildTools', '--add', 'Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools', '--add', 'Microsoft.VisualStudio.Workload.WebBuildTools', '--add', 'Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NetCoreBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NetCrossPlatBuildTools', '--add', 'Microsoft.VisualStudio.Workload.DataBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NodeBuildTools', '--add', 'Microsoft.VisualStudio.Workload.OfficeBuildTools', '--add', 'Microsoft.VisualStudio.Workload.PythonBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeDesktopBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeGameBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeMobileBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeCrossPlatBuildTools', '--add', 'Microsoft.VisualStudio.Workload.UniversalBuildTools', '--add', 'Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools', '--add', 'Microsoft.VisualStudio.Workload.WebBuildTools', '--add', 'Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NetCoreBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NetCrossPlatBuildTools', '--add', 'Microsoft.VisualStudio.Workload.DataBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NodeBuildTools', '--add', 'Microsoft.VisualStudio.Workload.OfficeBuildTools', '--add', 'Microsoft.VisualStudio.Workload.PythonBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeDesktopBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeGameBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeMobileBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeCrossPlatBuildTools' ; \
    Remove-Item -Force vs_installer.exe

# Set up the entry point
CMD ["cmd"]
